services:
  web:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/frontend"